name: health_care_chatbot
description: "A healthcare chatbot using Gemini AI."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  # State Management
  flutter_riverpod: ^2.4.9
  
  # Gemini AI
  google_generative_ai: ^0.2.2
  
  # Local Storage
  shared_preferences: ^2.2.2
  drift: ^2.26.0
  drift_flutter: ^0.2.4
  sqlite3_flutter_libs: ^0.5.20
  path_provider: ^2.1.2
  path: ^1.8.3
  
  # UI Enhancements
  flutter_chat_ui: ^1.6.10
  flutter_chat_types: ^3.6.2
  flutter_markdown: ^0.6.20
  
  # Utilities
  intl: ^0.19.0
  uuid: ^4.3.3
  url_launcher: ^6.3.1
  flutter_local_notifications: ^19.0.0
  timezone: ^0.10.0
  permission_handler: ^11.3.0
  rename_app: ^1.6.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  drift_dev: ^2.26.0
  build_runner: ^2.4.15

flutter:
  uses-material-design: true

assets:
  - .env
