name: health_care_chatbot
description: "A healthcare chatbot using Gemini AI."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  # State Management
  flutter_riverpod: ^2.4.9
  
  # Gemini AI
  google_generative_ai: ^0.2.2
  
  # Local Storage
  shared_preferences: ^2.2.2
  
  # UI Enhancements
  flutter_chat_ui: ^1.6.10
  flutter_chat_types: ^3.6.2
  
  # Utilities
  intl: ^0.19.0
  uuid: ^4.3.3
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

assets:
  - .env
